###
GET http://localhost:3003/api/blogs
###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Primer blog con Atlas",
  "author": "Roger",
  "url": "http://test.com",
  "likes": 5
}

###
GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Blog actualizado por modulos",
  "author": "Roger",
  "url": "http://roronoa.com",
  "likes": 5
}

###
GET http://localhost:3003/api/blogs

### Crear Usuario
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "RogiRP",
  "name": "Roger RP",
  "password": "secreto123"
}

### Lista usuarios
GET http://localhost:3003/api/users

